2.1.15

A random sample of 100 men is taken and their mean height is found to be 180 cm. The ***population variance*** is 36 cm square. Find the 95% confidence interval for the mean height of the population(μ).

(179.648, 183.760)

(178.248, 182.719)

(177.124, 180.178)

(178.824, 181.176) - x

In [13]:
# import the important packages
import pandas as pd  # library used for data manipulation and analysis
import numpy as np  # library used for working with arrays
import scipy.stats as stats  # this library contains a large number of probability distributions as well as a growing library of statistical functions
from scipy.stats import norm

import math

# Given data
x_bar = 180                 # sample mean (x bar)
population_variance  = 36   # population variance (population standard deviation (sigma) = square root of variance)
n = 100                     # sample size
confidence_level = 0.95     # confidence level

# Calculate population standard deviation
sigma = math.sqrt(population_variance)

# construct the confidence interval
np.round(norm.interval(confidence_level, loc=x_bar, scale=sigma / np.sqrt(n)), 2)

array([178.82, 181.18])

A landlord wants to rent an unfurnished one-bedroom apartment in Chicago. The mean monthly rent for a random sample of 100 apartments advertised on a website that lists apartments in Chicago for rent is $1000.

Assume a ***population standard deviation*** of $200. What is the 95% confidence interval for the mean rent?

(960.8, 1039.2) - x

(968.1, 1031.1)

(961.8, 1038.2)

(965.5, 1035.5)

In [14]:
# import the important packages
import pandas as pd  # library used for data manipulation and analysis
import numpy as np  # library used for working with arrays
import scipy.stats as stats  # this library contains a large number of probability distributions as well as a growing library of statistical functions
from scipy.stats import norm

import math

# Given data
x_bar = 1000                # sample mean (x bar)
sigma = 200                 # population standard deviation (sigma)
n = 100                     # sample size
confidence_level = 0.95     # confidence level

# construct the confidence interval
np.round(norm.interval(confidence_level, loc=x_bar, scale=sigma / np.sqrt(n)), 2)

array([ 960.8, 1039.2])

A survey of females aged 16-60 years was conducted by the Department of Population Censuses (DPC), it was found that a ***sample*** of fifty female students has a mean height of 160.9 cm with a ***standard deviation*** of 6 cm.

Determine the confidence interval of height with a confidence level of 95% and conclude whether their heights are typical to the general population.

(157.24,161.56) - Heights are typical to the general population

(159.19,162.61) - Heights are typical to the general population - x

(158.24,160.36) - Heights are typical to the general population

(150,162) - Heights are typical to the general population

In [15]:
# import the important packages
import pandas as pd  # library used for data manipulation and analysis
import numpy as np  # library used for working with arrays
import scipy.stats as stats  # this library contains a large number of probability distributions as well as a growing library of statistical functions

import math
from scipy.stats import t

# Given data
x_bar = 160.9              # sample mean (x bar)
sample_sigma = 6           # sample standard deviation
n = 50                     # sample size
confidence_level = 0.95    # confidence level

# Degrees of freedom
df = n - 1

# Calculate the t critical value
t_critical = t.ppf((1 + confidence_level) / 2, df)

# Calculate the margin of error
margin_of_error = t_critical * (sample_sigma / np.sqrt(n))

# Calculate the confidence interval
confidence_interval = (x_bar - margin_of_error, x_bar + margin_of_error)  # round the results to 2 decimal places

confidence_interval = np.round(confidence_interval, 2)

confidence_interval



array([159.19, 162.61])